apiVersion: apps/v1
kind: Deployment
metadata:
  name: zzzzz-deployment
  namespace: uvasds-services
  labels:
    app: zzzzz
spec:
  replicas: 8
  selector:
    matchLabels:
      app: zzzzz
  template:
    metadata:
      labels:
        app: zzzzz
    spec:
      containers:
      - name: zzzzz-container
        image: ghcr.io/nmagee/fastapi-demo:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "524Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: zzzzz-ingress
  namespace: uvasds-services
spec:
  rules:
  - host: zzzzz-api.pods.uvarc.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: zzzzz-service
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: zzzzz-service
  namespace: uvasds-services
spec:
  selector:
    app: zzzzz
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
