apiVersion: apps/v1
kind: Deployment
metadata:
  name: nem2p-dp1-deployment
  namespace: uvasds-services
  labels:
    app: nem2p-dp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nem2p-dp1
  template:
    metadata:
      labels:
        app: nem2p-dp1
    spec:
      containers:
      - name: nem2p-dp1-container
        image: ghcr.io/nmagee/fastapi-demo:1.101
        ports:
        - containerPort: 80
        env:
        - name: DBPASS
          value: sds_class27
#        - name: DBPASS
#          valueFrom:
#            secretKeyRef:
#              name: dp1pass
#              key: DBPASS
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: nem2p-dp1-ingress
  namespace: uvasds-services
spec:
  rules:
  - host: nem2p-dp1-api.pods.uvarc.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nem2p-dp1-service
            port:
              number: 8080
  - host: nem2p-dp1-api.sds.pods.uvarc.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nem2p-dp1-service
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nem2p-dp1-service
  namespace: uvasds-services
spec:
  selector:
    app: nem2p-dp1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
