---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: first-secret
  namespace: uvasds-services
spec:
  encryptedData:
    fname: AgCE1eZp9V4may/XUQD4m1cEfhP9A1ppMmaIKwtZ3xpyJuj2BrJhrxiDsaca5z/QKsVZ3h7NCwV3k+hMZBuA9XZ3eN8KjLyxOkhRdUBoVjh8QKYSnz8vmFM7eoYRI/MjA16EYZWYDbL6fVRVK6p2cEEHGetwzDEmeYLU3n4hk7v5TeILhiKUXcfdwJudbAN2qXRJnCUnGUix0oto3coxPavzzbwV8xNl9KwOTvv6ahosXfz9rGldNQ67uelGyc1uuSdatR+o1xtnZt6r+pWuTSDP2EnAaFiPxU0gzNDbowXKQ6ZJ6xW6lCvVLEgAyCWIf94u1oFgG3P5Ywr+kddlqa/pgL3/mZPUc2s0o6+StaT7xAQBDfO17MkTyWyh94Jzdy2wv6Utkre/+K+N6lgMwcc6ArBdpNYnv2PBLcw95Uorbvz8Wr3o2VAq68hMYzJ/L6iNBZqyQWS/yjHStcKnB/q151yNRdV0tA+yMEdtOe99bc2ITTbmwH0iAFdfr2iDzZzs9ZlObQxcIXv1k6qOqZZPqP1AzwqGmTNTg8JKENz4b/3ADyVYhClHNRajoV3hs1NkBQyNoCWQIjYtkQZ//iycT1/zWkHNcxl//qJWyKnXz9UvP0EduuWB2vbmDYhOsP1u3B+XW6r3QS9yQyccHAIjqnuOCTzoVWLLjYJlaKCUBHqsyjnxxSkqkDInK229ol7X9lauzg==
    lname: AgBwh7B+umyiWj4/PAMvDnqtphAqPoDuDv72is6H/tCLp5jBOqOAQEC+HEwiRFBzE+f/XtPUM5+R9cyZ4QLS07Nv0Xufwi1sBXPtUcmQMVQtWBWVBzOp1+c3nByxFbN10nxwoyBKdT31i0nkzaJTmMMoTMmE3jn2dMdLbhwUE2JuGj/vJiXAcZkjqqlwDBjbcGXG5EZnh/HnAMn3zhm+a0u2wV2NAWIcsOooGUtVkPoOIbWTeoq2FxiXANuegbLitLTZzJeZ6WHfW07llgKqys7X40oP5GBG3U8aNmlkHoO4SoxEGHZ/FZIxATNN7fU8MJBWzBwMDPrv4FW24cfIdYuOlWoO67gAdX8duhJ/+Y0eLkhL+2U2gLzoExygw5200NXORd2YJvFmylln20n9mjF9v825I0SV/NeHQ5epTxT04ftxpDVisvRaCnzgoW4LXknAzWKiQPyIioB0XmivlotjJz9pBrpElc+Eo/UUDK+sG+TCwbb9kppFYPIf/bilwZDcU3N+zzPi0XNGCthck1CkXRt9YxGcUgqM4/ASdXjVtXuHY7DAY1t84pbKzE4JRzQ0+OTE3ZqPJIFkfSxTEdc1jtaXvlprtGkvN10wUWW/VAWuBj4/s+/Zw7QVtsRXw3EJOh7vc1iSbRa5RPf+Qgp7UzGAtSACqAtfl85rSmjvezVuM7SbkIYlp8e4PUP7uhTYdslQ85M=
  template:
    metadata:
      creationTimestamp: null
      name: first-secret
      namespace: uvasds-services
