apiVersion: apps/v1
kind: Deployment
metadata:
  name: kupperman-deployment
  namespace: uvasds-services
  labels:
    app: kupperman-demo
spec:
  replicas: 12
  selector:
    matchLabels:
      app: kupperman-demo
  template:
    metadata:
      labels:
        app: kupperman-demo
    spec:
      containers:
      - name: kupperman-container
        image: uvarc/accord-demo
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "524Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: kupperman-ingress
  namespace: uvasds-services
spec:
  rules:
  - host: bananas.pods.uvarc.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: kupperman-service
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kupperman-service
  namespace: uvasds-services
spec:
  selector:
    app: kupperman-demo
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
