apiVersion: batch/v1
kind: CronJob
metadata:
  name: ds2002-directory-merge
  namespace: uvasds-services
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ds2002-merge
            image: ghcr.io/nmagee/ds2002-directory:v4
            imagePullPolicy: Always
            envFrom:
            - secretRef:
                name: nem2p-pat
            resources:  
              limits:   
                cpu: "0.5"
                memory: 512Mi
              requests: 
                cpu: "0.5"
                memory: 512Mi
          restartPolicy: Never
      ttlSecondsAfterFinished: 10800
