apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustapi-deployment
  namespace: uvasds-services
  labels:
    app: rust-api
spec:
  replicas: 0
  selector:
    matchLabels:
      app: rust-api
  template:
    metadata:
      labels:
        app: rust-api
    spec:
      containers:
      - name: rustapi-container
        image: ghcr.io/nmagee/rust-api:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "524Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  name: rustapi-ingress
  namespace: uvasds-services
spec:
  rules:
  - host: rust-api.pods.uvarc.io
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: rustapi-service
            port:
              number: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rustapi-service
  namespace: uvasds-services
spec:
  selector:
    app: rust-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
