apiVersion: apps/v1
kind: Deployment
metadata:
  name: id-generator-deployment
  namespace: uvasds-services
  labels:
    app: id-generator
spec:
  replicas: 10
  selector:
    matchLabels:
      app: id-generator
  template:
    metadata:
      labels:
        app: id-generator
        environment: production
        owner: nem2p
        team: uvasds
    spec:
      containers:
      - name: id-generator-container
        image: ghcr.io/uvarc/id-generator:{{ .Values.version.idGenerator }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "2048Mi"
            cpu: "1000m"
          limits:
            memory: "4096Mi"
            cpu: "2000m"
      imagePullSecrets:
      - name: nmagee-ghcr.io-auth
