apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-demo-deployment
  namespace: uvasds-services
  labels:
    app: fastapi-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-demo
  template:
    metadata:
      labels:
        app: fastapi-demo
    spec:
      containers:
      - name: fastapi-demo-container
        image: ghcr.io/nmagee/fastapi-demo:1.89
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "524Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"
