name: Remote Dispatch Action

on:
  pull_request:
    types: [opened, reopened]
    paths:
      - '!uvasds-services/templates/ds2002/**'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: "We do not accept PRs outside of the DS2002 folder."
